# Generated by Django 4.2.1 on 2024-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.CharField(max_length=12),
        ),
    ]
