# Generated by Django 4.2.1 on 2024-05-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetcode',
            name='generated_reset_code',
            field=models.PositiveIntegerField(),
        ),
    ]
