# Generated by Django 4.2.1 on 2024-05-11 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_buscompany_company_bus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=20)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('available_seats', models.PositiveSmallIntegerField()),
                ('departure_location', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('departure_time', models.TimeField()),
                ('fare', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.buscompany')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
